xcopy /Y HomeManagement.Web\bin "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\bin\"
xcopy /Y /E HomeManagement.Web\Content "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\Content\"
xcopy /Y /E HomeManagement.Web\Scripts "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\Scripts\"
xcopy /Y /E HomeManagement.Web\Views "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\Views\"
xcopy /Y HomeManagement.Web\Global.asax "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\"
xcopy /Y HomeManagement.Web\favicon.ico "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\"
xcopy /Y HomeManagement.Web\packages.config "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\"
xcopy /Y HomeManagement.Web\Web.config "C:\Documents and Settings\ForumAdmin\My Documents\My Web Sites\Home Management\"
